// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlrkmumqbdyjlbzxpqqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRscmttdW1xYmR5amxienhwcXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzNzk1NzgsImV4cCI6MjA2Nzk1NTU3OH0.ggCmTAE2cHEKnBuRnnWGWHDl1E7ZwEr2Aixa99QVd_w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});